language: go
go:
- '1.3'
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- go get ./...
script:
- go test -v
after_success:
  - go get github.com/laher/goxc
  - goxc -t -bc="windows linux darwin,\!arm"
  - goxc -pv=${TRAVIS_TAG} -n=42minutes -bc="windows linux darwin,\!arm" -d="dist/"

deploy:
  provider: releases
  api_key:
    secure: wjqdiTdyrjdXETsvfEfHyGS7E/KnS8iqto+NdwRa/OWraUufp0oGoiPGwL3juzlorIbffJI+K0XDoZzX5JtLHG2PX4zzig3seF2ABd/KRlh1EXo2veYKixVM5+1WMjPvEkrfjeXOI9sEPmatcsoQqKa/HjXe7knbI00/kTqptF8=
  file_glob: true
  file: dist/${TRAVIS_TAG}/*
  on:
    repo: 42minutes/42minutes-client
    all_branches: true
    tags: true
